### ISSUE TITLE
Flag for Double Ammo Explosion Chance

### ISSUE THREAD

**Issue by LadyAlekto** [BattletechModders/CBTBehaviorsEnhanced#1]
So after our little talk

A big issue is checking for HeatDamagerPerAmmo on ammo boxes as i use a mix of all 3 damages to balance explosions, not just for inferno rounds

A better more flexible way would be a new custom flag that when checked, defines this box as extra volatile (aka does the doubled roll)

And for other users, id say a toggle in mod.json between either method

*edit*
*edit2* disregard this second part then, since you explained to me how stupid it would be, i be sad gameplay designer and accept the fate ;)

the ultimate option would be customcomponents flag for ammo boxes that makes them more or less likely to explode

Solution could be, roll is made, CBTBE checks all boxes for their chance, and detonates the first it has a "success" roll on

**Comment by IceRaptor** [comment]
Fixed in 0.3.3 - looks for `VolatileAmmo` component. Only components with these values are subject to the second roll.
