### ISSUE TITLE
Mechs not acted autobrace when transitioning between Out-of-combat to In-combat turn systems

### ISSUE THREAD

**Issue by Poodmund** [BattletechModders/CBTBehaviorsEnhanced#10]
When the first mech in your lance moves from Out-of-combat to In-combat and triggers the combat turn system, any of your mechs that have not yet acted in that Out-of-combat turn automatically end their turn and Autobrace, thus losing all of their current Evasion pips that they may have built up.

This can cause major issues when, for example, the newly encountered enemy lance has better initiative and then rush your lance members with zero evasion on that first combat turn.

See a video of this issue occurring here: [Link](https://youtu.be/ELsRFzYBTWI)

In the video none of the mechs have currently moved in this Out-of-combat turn but all have built up Evasion pips on the previous Out-of-combat turn. The Grasshopper piloted by 'Bast' is the first lance member to move in this Out-of-combat turn and encounters the OpFor and triggers the switch from Out-of-combat to In-combat. This switch causes all the other lance members to automatically end their turn and 'Guard' but lose all their Evasion pips doing so.

Logs attached: I loaded the game, loaded a career save and started and restarted a couple of missions to spawn in locations that would cause this issue. Then I forced the issue by moving the mechs as shown in the video. I completed 1 turn of In-combat and then quit the game to desktop. Hopefully that background may help identifying where the issue may lie.

[output_log.txt](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4042334/output_log.txt)

[cleaned_output_log.txt](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4042335/cleaned_output_log.txt)

[ModTek.log](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4042336/ModTek.log)

Potential culprit area may be: https://github.com/IceRaptor/CBTBehaviorsEnhanced/blob/master/CBTBehaviorsEnhanced/CBTBehaviorsEnhanced/Patches/MovementPatches.cs#L75-L125 ???

If you'd like me to set up a completely Vanilla install only with CBTBE and ModTek installed to get some logs and reproduce please let me know.

Thanks for all your work and efforts :D

**Comment by IceRaptor** [comment]
Should be fixed with 0.3.12 release.
