### ISSUE TITLE
Cannot clic on button reserve

### ISSUE THREAD

**Issue by Lemril** [BattletechModders/CBTBehaviorsEnhanced#105]
In version 0.8.0 I cannot click on the button RESERVE. 
in version 0.7.0 I work.

In the UI log, it shows that it thinks to be a melee selector button
`CHUDFB - OnClick FIRED for FireMode: Reserve`

**Comment by IceRaptor** [comment]
This should be fixed in the latest 0.8.10 release. Thanks for the report!
