### ISSUE TITLE
Internal component destruction is ignoring CC ignore_damage flag

### ISSUE THREAD

**Issue by bloodydoves** [BattletechModders/CBTBehaviorsEnhanced#18]
Just what it says on the tin: we think that CBTBE's heat based internal component destruction is ignoring the CustomComponents ignore_damage flag. This can cause a rare pseudo-softlock when a component is destroyed that gives the unit bonus structure and the loss of that bonus structure leads to the death of the unit. The game doesn't recognize what happened and the unit becomes a half-dead/half-alive zombie unit.

**Comment by LadyAlekto** [comment]
It could also destroy components that supposedly cannot be destroyed like case system and quirks

**Comment by IceRaptor** [comment]
Should be fixed in 0.3.10, but needs testing.
