### ISSUE TITLE
Fallen down, dies and doesnt die NRE

### ISSUE THREAD

**Issue by taintedloki** [BattletechModders/CBTBehaviorsEnhanced#19]
User ran into this upon knocking down a banshee, it toke enough head damage to be killed with an NRE at that time.

**Comment by taintedloki** [comment]
[cbt_behaviors_enhanced.log](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4097235/cbt_behaviors_enhanced.log)
[Uploading cleaned_output_log-2.txt…]()
[Uploading output_log-2.txt…]()

**Comment by taintedloki** [comment]
[cbt_behaviors_enhanced.log](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4102707/cbt_behaviors_enhanced.log)
[cleaned_output_log.txt](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4102708/cleaned_output_log.txt)
[output_log.txt](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4102709/output_log.txt)
another set to go with it for more information

**Comment by IceRaptor** [comment]
This is all related to me not sending actor death messages when damaging pilots. Also happens with heat damage.

**Comment by IceRaptor** [comment]
Fixed locally, will be available in the 0.5.0 release.
