### ISSUE TITLE
AI Mechs that shut down at the end of their turn can immediately restart.

### ISSUE THREAD

**Issue by MartenKahr** [BattletechModders/CBTBehaviorsEnhanced#23]
As the title suggests, AI Mechs can restart immediately after failing a shutdown check.
Seems to happen if an AI Mech is so overheated that they only move on their turn, without taking a shot.

Attached logs demonstrate a Shadowhawk doing exactly that.
[HeatRestartBug.zip](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4198764/HeatRestartBug.zip)

**Comment by IceRaptor** [comment]
Should be fixed in 0.4.6
