### ISSUE TITLE
return of the knockdown bug in 1.9

### ISSUE THREAD

**Issue by taintedloki** [BattletechModders/CBTBehaviorsEnhanced#27]
destroyed the leg on the jenner, it falls then starts to slide around instead of standing back up
[output_log.txt](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4270945/output_log.txt)
[cleaned_output_log.txt](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4270946/cleaned_output_log.txt)
[harmony_summary.log](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4270947/harmony_summary.log)
[ModTek.log](https://github.com/IceRaptor/CBTBehaviorsEnhanced/files/4270948/ModTek.log)

2020-02-29T13:01:26 FYLS [LOG] Actor Jenner (358c5692-25ee-433b-b9ce-bab9ae35528e.0) - Jenner (358c5692-25ee-433b-b9ce-bab9ae35528e.0) FLAGGED FOR KNOCKDOWN!

**Comment by taintedloki** [comment]
if you need any other logs let me know

**Comment by IceRaptor** [comment]
Fixed in 0.4.3.
