### ISSUE TITLE
Not even sure how to describe these issues; REL_0.5.6, with default mod.json settings

### ISSUE THREAD

**Issue by TimeDiver0** [BattletechModders/CBTBehaviorsEnhanced#53]
EDIT: As of REL_0.5.6, movement (normal, sprinting and jumping) is now possible, though no movement preview is shown.

In addition, the 'only the 1st weapon is displayed' bug continues to persist (and cannot fire any weapons otherwise).

My mod list remains unchanged, save for newer releases; the output_log.txt file is far smaller this time ('only' ~4.7 MiB): [output_log.txt](https://github.com/BattletechModders/CBTBehaviorsEnhanced/files/4848679/output_log.txt)

Well, a picture being a thousand words and all (random lance in single-player unlimited value Skirmish mode):

https://imgur.com/a/OLFHZGk

In more detail: _only_ the first weapon is being shown for any selected unit, and (NOT shown in the screenie) **none** of the units are able to move.

My mod list from \Mods\ .modtek\load_order.json (all the latest versions, that I could find on GitHub and NexusMods):

[
  "ModTek",
  "SkipIntro",
  "BattletechPerformanceFix",
  "cFixes",
  "CustomComponents",
  "IRBTModUtils",
  "MechEngineer",
  "AbilityRealizer",
  "AddYearToTimeline",
  "AdjustedMechAssemblyCC",
  "AdjustedMechSalvage",
  "Armor",
  "AugmentedEvents",
  "CommanderPortraitLoader",
  "ContractSort",
  "LootMagnet",
  "MechMaintenanceByCost",
  "Monthly Tech Adjustment",
  "Repair Bays",
  "Retrainer",
  "SpeedMod",
  "MechResizer",
  "VehicleImprovementProject",
  "JK_VariantsCampaign",
  "JK_VariantsSkirmish",
  "WeaponDiversity + +",
  "CBTBehaviorsEnhanced",
  "Custom Ammo Categories",
  "ExpandedInitiative",
  "PanicSystem",
  "PermanentEvasion",
  "StabilityTonnage",
  "Better AI",
  "Better AI Permanent Evasion Add-on",
  "CleverGirl",
  "IRTweaks",
  "LittleThings",
  "Pilot Quirks"
]

If you require the output_log.txt file, I'll link to it (although it's 30+ MiB in size, uncompressed):

http://www.mediafire.com/file/s7o0qkz2x0j38lf/output_log.zip/file

**Comment by IceRaptor** [comment]
You're using an obsolete version of IRBTModUtils. You need to download the latest from https://github.com/battletechmodders/irbtmodutils/ and it will solve this issue.
