### ISSUE TITLE
0 damage DFA attack

### ISSUE THREAD

**Issue by BlueWinds** [BattletechModders/CBTBehaviorsEnhanced#56]
A Grasshopper showed 0 damage for its DFA attack when I selected an enemy, and in fact did 0 when I jumped on them. Normal DFA is 140 damage for this mech, in BTA settings, and this is the value that shows up in the GUI most of the time.

Opening a ticket so the logs don't get lost.

[0DamageDFA.zip](https://github.com/BattletechModders/CBTBehaviorsEnhanced/files/4841177/0DamageDFA.zip)
![Screenshot_20200627_095424](https://user-images.githubusercontent.com/3003404/85931113-ae692700-b876-11ea-82c6-0df5e4005767.png)

**Comment by IceRaptor** [comment]
Fixed in 0.5.27
