### ISSUE TITLE
support weapons during kicks always target legs as well

### ISSUE THREAD

**Issue by taintedloki** [BattletechModders/CBTBehaviorsEnhanced#61]
v5.6.1 while kicking support weapons also fire so target the legs. 
[Knees.zip](https://github.com/BattletechModders/CBTBehaviorsEnhanced/files/4901402/Knees.zip)

video of it as well from user https://discordapp.com/channels/587764595888881670/587765800052457474/731033046450700328

**Comment by IceRaptor** [comment]
Should be fixed in 0.5.13
