### ISSUE TITLE
Enhancement Request: Would like a series of stats that permit reduction of melee damage taken

### ISSUE THREAD

**Issue by bloodydoves** [BattletechModders/CBTBehaviorsEnhanced#62]
Basically, I'd like a stat for each melee attack type that permits damage taken by the target to be reduced by a float_add or float_multiply. Pretty much what it says on the tin, nothing fancy here. Would be nice at some point.

**Comment by IceRaptor** [comment]
Added in 0.6.0

`CBTBE_Charge_Target_Damage_Reduction_Multi` and `CBTBE_Charge_Target_Instability_Reduction_Multi`
`CBTBE_DFA_Target_Damage_Reduction_Multi` and `CBTBE_DFA_Target_Instability_Reduction_Multi`
- This applies to attacker as well as target for attacker self-damage from charge, DFA
`CBTBE_Kick_Target_Damage_Reduction_Multi` and `CBTBE_Kick_Target_Instability_Reduction_Multi`
`CBTBE_Punch_Target_Damage_Reduction_Multi` and `CBTBE_Punch_Target_Instability_Reduction_Multi`
`CBTBE_Physical_Weapon_Target_Damage_Reduction_Multi` and `CBTBE_Physical_Weapon_Target_Instability_Reduction_Multi`
