### ISSUE TITLE
Could fire after falling down

### ISSUE THREAD

**Issue by IceRaptor** [BattletechModders/CBTBehaviorsEnhanced#69]
Per a report from MrBigots in roguetciket-1186, they could fire after failing a knockdown check from jumping. Activation didn't complete after the knockdown sequence, and they were allowed to continue their turn. They were the last unit in the round.

**Comment by IceRaptor** [comment]
[RogueLogs.zip](https://github.com/BattletechModders/CBTBehaviorsEnhanced/files/5434683/RogueLogs.zip)

**Comment by LadyAlekto** [comment]
![image](https://user-images.githubusercontent.com/39632036/97107287-13b71280-16c7-11eb-8537-31aade15a2b9.png)

**Comment by IceRaptor** [comment]
Fixed in 0.5.24.
