### ISSUE TITLE
Show HeatsinkCapacity in the Heat Panel

### ISSUE THREAD

**Issue by LadyAlekto** [BattletechModders/CBTBehaviorsEnhanced#8]
Basically a way to give more information to players to show them their current heat sink capacity (like in a bad biome or when hit with infernos that reduce it etc)

![20200106232614_1](https://user-images.githubusercontent.com/39632036/71853662-698ce080-30dc-11ea-8006-da4cd7061ea9.jpg)

**Comment by IceRaptor** [comment]
Added in 0.3.8
